version: '3.9'

services:

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8080:8080"
    volumes:
      - filestorage:/filestorage:/data
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=3dcon
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: "always"

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    command: npm start
    depends_on:
        - backend

volumes:
  postgres:
    name: postgres
  filestorage:
    name: filestorage