version: '3.9'

services:

  backend:
    container_name: backend_internal
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "8080:8080"
    volumes:
      - filestorage:/filestorage:/data
    depends_on:
      - postgres

  postgres:
    container_name: postgres_internal
    image: postgres:latest
    environment:
      - POSTGRES_DB=golang
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: "always"

volumes:
  postgres:
    name: postgres
  filestorage:
    name: filestorage