basePath: /
definitions:
  auth.JoinModel:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  auth.LoginModel:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  product.ModelDto:
    properties:
      cover_url:
        type: string
      created_at:
        type: string
      description:
        type: string
      licence:
        type: string
      likes_count:
        type: integer
      name:
        type: string
      owner:
        $ref: '#/definitions/user.ModelDto'
      price:
        type: number
      views_count:
        type: integer
    type: object
  user.ModelDto:
    properties:
      avatar_url:
        type: string
      email:
        description: TODO
        type: string
      role:
        type: string
      sales_count:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: 3Dcon
paths:
  /account/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ModelDto'
      security:
      - ApiKeyAuth: []
      tags:
      - account
  /auth/join:
    post:
      consumes:
      - application/json
      parameters:
      - description: join
        in: body
        name: Join
        required: true
        schema:
          $ref: '#/definitions/auth.JoinModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/auth.LoginModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - auth
  /filestorage/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - filestorage
  /helloworld:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - helloworld
  /products/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ModelDto'
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - product
  /products/my:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product.ModelDto'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - product
  /products/upload:
    post:
      consumes:
      - multipart/form-data
      operationId: product.upload
      parameters:
      - description: cover
        in: formData
        name: cover
        required: true
        type: file
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: licence
        in: formData
        name: licence
        required: true
        type: string
      - description: description
        in: formData
        name: description
        required: true
        type: string
      - description: price
        in: formData
        name: price
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      tags:
      - product
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
